/**
 * Blank markers for fill-in-the-blank passages.
 *
 * Passages are generated by Gemini, which is asked to emit `__BLANK_0__`, `__BLANK_1__`, ...
 * in place of each vocabulary word. It does not always comply: a mistyped marker such as
 * `__BLAK_4__` stays in the passage as literal text, so the student can never fill that
 * blank. Everything that reads or writes a marker goes through this module so the format
 * is defined once.
 */

/** Canonical marker for a blank at `index`. */
export const blankMarker = (index: number): string => `__BLANK_${index}__`;

/** Splits a passage into alternating text and marker segments, keeping the markers. */
export const splitPassage = (passage: string): string[] => passage.split(/(__BLANK_\d+__)/g);

/** The blank index of a segment from `splitPassage`, or null when it is plain text. */
export const blankIndexOf = (segment: string): number | null => {
  const match = segment.match(/^__BLANK_(\d+)__$/);
  return match ? Number(match[1]) : null;
};

/** Every well-formed blank index in the passage, in order of appearance. */
export const parseBlankIndices = (passage: string): number[] =>
  [...passage.matchAll(/__BLANK_(\d+)__/g)].map(match => Number(match[1]));

/**
 * Any underscore-wrapped token carrying an index, which is what a mistyped marker
 * degrades into. Prose never looks like this, and a repair is only ever kept when the
 * result validates, so matching loosely here is safe.
 */
const MARKER_LIKE = /_{1,3}\s*[A-Za-z]{0,8}\s*_{0,2}\s*(\d+)\s*_{1,3}/g;

/** Rewrites mistyped markers (`__BLAK_4__`, `__BLANK4__`) back to canonical form. */
export const repairBlankMarkers = (passage: string): string =>
  passage.replace(MARKER_LIKE, (match, index) =>
    blankIndexOf(match) === null ? blankMarker(Number(index)) : match
  );

/**
 * Describes why `passage` cannot be solved against `answers`, or null when it can.
 * Solvable means exactly one marker per answer: `__BLANK_0__` through `__BLANK_{n-1}__`.
 */
export const describeBlankMismatch = (passage: string, answers: string[]): string | null => {
  const found = parseBlankIndices(passage);
  const unique = new Set(found);

  if (unique.size !== found.length) return `duplicate markers: ${found.join(', ')}`;

  const missing = answers.map((_, i) => i).filter(i => !unique.has(i));
  const unexpected = found.filter(i => i >= answers.length);
  if (missing.length || unexpected.length) {
    return [
      `expected ${answers.length} markers`,
      missing.length ? `missing ${missing.map(blankMarker).join(', ')}` : '',
      unexpected.length ? `unexpected ${unexpected.map(blankMarker).join(', ')}` : '',
    ].filter(Boolean).join('; ');
  }
  return null;
};

/**
 * Prepares a stored passage for display: repairs mistyped markers and reports the blanks
 * the student can actually fill. Callers must size progress off `indices` rather than
 * `answers.length` - a passage that lost a marker has fewer blanks than answers, and
 * waiting for the missing one would leave the student stuck forever.
 */
export const prepareBlankPassage = (
  passage: string | undefined,
  answers: string[]
): { passage: string; indices: number[] } => {
  const repaired = repairBlankMarkers(passage ?? '');
  const indices = parseBlankIndices(repaired);
  // Keep the repair only when it produced a passage that matches the answers.
  if (describeBlankMismatch(repaired, answers) && !describeBlankMismatch(passage ?? '', answers)) {
    return { passage: passage ?? '', indices: parseBlankIndices(passage ?? '') };
  }
  return { passage: repaired, indices };
};
